In [ ]:
# !pip install lightfm

In [ ]:
from lightfm.datasets import fetch_movielens
from lightfm import LightFM
import numpy as np
import pandas as pd

# Data

This dataset (movielens) describes 5-star rating and free-text tagging activity from MovieLens, a movie recommendation service. It contains 25000095 ratings and 1093360 tag applications across 62423 movies. These data were created by 162541 users between January 09, 1995 and November 21, 2019. This dataset was generated on November 21, 2019.

Users were selected at random for inclusion. All selected users had rated at least 20 movies. No demographic information is included. Each user is represented by an id, and no other information is provided.

The data are contained in the files genome-scores.csv, genome-tags.csv, links.csv, movies.csv, ratings.csv and tags.csv. More details about the contents and use of all these files follows.

This and other GroupLens data sets are publicly available for download at http://grouplens.org/datasets/.


In [ ]:
%%time
movies = fetch_movielens(min_rating=4)

CPU times: user 796 ms, sys: 24.8 ms, total: 821 ms
Wall time: 1.23 s


In [ ]:
movies_transactions = pd.DataFrame.sparse.from_spmatrix(movies['train'], columns = movies['item_feature_labels']).astype(bool)
movies_transactions

Toy Story (1995)  ...  Scream of Stone (Schrei aus Stein) (1991)
0                True  ...                                      False
1                True  ...                                      False
2               False  ...                                      False
3               False  ...                                      False
4               False  ...                                      False
..                ...  ...                                        ...
938             False  ...                                      False
939             False  ...                                      False
940              True  ...                                      False
941             False  ...                                      False
942             False  ...                                      False

[943 rows x 1682 columns]

##Exercise 1. Association Rules / Apriori. 
Having the previous Dataset that tell us if a user (row) has what a film (True) or not (False). 

What is the pair of films with higher support?. Explain what is the support

In [ ]:
from mlxtend.frequent_patterns import apriori
# your code here

support                                           itemsets  n_items
304  0.292683      (Return of the Jedi (1983), Star Wars (1977))        2
300  0.254507  (Raiders of the Lost Ark (1981), Star Wars (19...        2
298  0.237540  (Empire Strikes Back, The (1980), Star Wars (1...        2
286  0.231177  (Silence of the Lambs, The (1991), Star Wars (...        2
287  0.217391                   (Fargo (1996), Star Wars (1977))        2
..        ...                                                ...      ...
755  0.100742                       (Aliens (1986), Jaws (1975))        2
382  0.100742  (Pulp Fiction (1994), E.T. the Extra-Terrestri...        2
634  0.100742  (Wizard of Oz, The (1939), One Flew Over the C...        2
671  0.100742   (Psycho (1960), Empire Strikes Back, The (1980))        2
777  0.100742  (Return of the Jedi (1983), To Kill a Mockingb...        2

[673 rows x 3 columns]

##Exercise 2. Association Rules / Apriori. 
once we have calculated the apriori, what is the relation with the highest confidence ? . What's the confidence?

In [ ]:
from mlxtend.frequent_patterns import association_rules
# your code here

antecedents  ... conviction
755  (Pulp Fiction (1994), Return of the Jedi (1983...  ...   9.557264
402  (Return of the Jedi (1983), Princess Bride, Th...  ...   8.738070
883  (Return of the Jedi (1983), Princess Bride, Th...  ...   8.260207
931  (Raiders of the Lost Ark (1981), Return of the...  ...   7.987142
473  (Return of the Jedi (1983), E.T. the Extra-Ter...  ...   7.918876

[5 rows x 9 columns]

##Exercise 3. Association Rules / Apriori. 
what is the relation with the highest lift ? . What's the lisf? (check it out [here](https://www.ibm.com/support/knowledgecenter/SSEPGG_9.7.0/com.ibm.im.model.doc/c_lift_in_an_association_rule.html) and explain it )

In [ ]:
# you code here

antecedents  ... conviction
4694  (Raiders of the Lost Ark (1981), Terminator 2:...  ...   2.267939
4699  (Terminator, The (1984), Empire Strikes Back, ...  ...   2.571142
4695  (Raiders of the Lost Ark (1981), Terminator, T...  ...   1.957263
4698  (Terminator 2: Judgment Day (1991), Empire Str...  ...   2.519134
3873         (Aliens (1986), Return of the Jedi (1983))  ...   4.704750

[5 rows x 9 columns]

frozenset({'Raiders of the Lost Ark (1981)',
           'Terminator 2: Judgment Day (1991)'})

frozenset({'Empire Strikes Back, The (1980)', 'Terminator, The (1984)'})

# Let's see the structure of the data
The dataset is an object with 5 elements. 
* `item_feature_labels` a list of the movie names
* `item_features` an sparse matrix with all the rating each user has given to each movie
* `item_labels`  (a list of the movie namem, the same as `item_feature_labels`)
* `test` an sparse matrix with all the rating each user has given to each movie for test
* `train` an sparse matrix with all the rating each user has given to each movie for train

*** 
We are going to use 
* `item_feature_labels`
* `train` 
* `test`

In [ ]:
movies['train']

<943x1682 sparse matrix of type '<class 'numpy.int32'>'
	with 49906 stored elements in COOrdinate format>

## Let's use the test data to play with it

In [ ]:
df = pd.DataFrame.sparse.from_spmatrix(movies['test'],columns=movies['item_feature_labels'])
df

Toy Story (1995)  ...  Scream of Stone (Schrei aus Stein) (1991)
0                   0  ...                                          0
1                   0  ...                                          0
2                   0  ...                                          0
3                   0  ...                                          0
4                   4  ...                                          0
..                ...  ...                                        ...
938                 0  ...                                          0
939                 0  ...                                          0
940                 0  ...                                          0
941                 0  ...                                          0
942                 0  ...                                          0

[943 rows x 1682 columns]

## Tidy the data

In [ ]:
df = df.melt(var_name='movie', value_name='freq')
df = df[df['freq']>0]
df

movie  freq
4                                         Toy Story (1995)     4
16                                        Toy Story (1995)     4
94                                        Toy Story (1995)     5
108                                       Toy Story (1995)     4
130                                       Toy Story (1995)     4
...                                                    ...   ...
1500831                             Magic Hour, The (1998)     5
1520092                            Leading Man, The (1996)     4
1524406                                   Hugo Pool (1997)     5
1552062                               Men With Guns (1997)     4
1558510  Entertaining Angels: The Dorothy Day Story (1996)     5

[5469 rows x 2 columns]

## Top ten most watched movies

In [ ]:
aux = df.groupby(['movie']).agg(n=('freq','sum')).reset_index()
aux.sort_values('n',ascending=False).head(10)

movie    n
743             Star Wars (1977)  340
171               Contact (1997)  297
790               Titanic (1997)  265
337        Godfather, The (1972)  247
271                 Fargo (1996)  241
652    Return of the Jedi (1983)  217
248  English Patient, The (1996)  211
803             Toy Story (1995)  198
313       Full Monty, The (1997)  193
673                Scream (1996)  192

# Create the rec sys

### LigthFM main attributes
***

* **no_components** (int, optional) – the dimensionality of the feature latent 
embeddings. It is simliar to the concept of `component` in `PCA`. It determines the number of `latent_features` in which we *summarise* the rataing matrix

* **learning_schedule** (string, optional) – one of (`adagrad`, `adadelta`). It is the name of the descent gradient algorithm we use to make the recommendation system converge
* **loss** (string, optional) – one of (`logistic`, `bpr`, `warp`, `warp-kos`): the loss function.
    * **logistic**: useful when both positive (1) and negative (-1) interactions are present.
    * **BPR**: Bayesian Personalised Ranking [1]_ pairwise loss. Maximises the
prediction difference between a positive example and a randomly 
chosen negative example. Useful when only positive interactions 
are present and optimising ROC AUC is desired.
    * **WARP**: Weighted Approximate-Rank Pairwise [2]_ loss. 
Maximises the rank of positive examples by repeatedly sampling negative 
examples until rank violating one is found. Useful when only 
positive interactions are present and optimising the top of 
the recommendation list (precision@k) is desired.
    * **k-OS WARP**: k-th order statistic loss [3]_.
A modification of WARP that uses the k-th positive example for any given user as a basis for pairwise updates.




* **item_alpha** (float, optional) – L2 penalty on item features. Tip: setting this number too high can slow down training. One good way to check is if the final weights in the embeddings turned out to be mostly zero. The same idea applies to the user_alpha parameter.
* **user_alpha** (float, optional) – L2 penalty on user features.
max_sampled (int, optional) 
* **random_state** (int seed, RandomState instance, or None) – The seed of the pseudo random number generator to use when shuffling the data and initializing the parameters.

In [ ]:
%%time
from lightfm import LightFM
rec_sys = LightFM(loss='warp',learning_schedule='adadelta',random_state=101)
# fit the model
rec_sys.fit(movies['train'], epochs=30, num_threads=2,)

CPU times: user 2.35 s, sys: 1.05 ms, total: 2.36 s
Wall time: 1.21 s


In [ ]:
movies['train'].shape

(943, 1682)

# Let's see how the rec_sys *predict* (it is not a prediction)

In [ ]:
# let's take an user_id
user_id = 0 

In [ ]:
# let's see the movies this user has watched
movies['item_labels'][movies['train'].tocsr()[user_id].indices][:10]

array(['Toy Story (1995)', 'Four Rooms (1995)',
       'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)',
       'Twelve Monkeys (1995)', 'Dead Man Walking (1995)',
       'Usual Suspects, The (1995)', 'Mighty Aphrodite (1995)',
       'Postino, Il (1994)', "Mr. Holland's Opus (1995)",
       'French Twist (Gazon maudit) (1995)'], dtype=object)

In [ ]:
# let's give a score to each movie (a probability that this user wouls watch the movie)
n_items= movies['train'].shape[1]
n_items

1682

In [ ]:
# let's predict the score the user would give to all movies
scores = rec_sys.predict(user_id, np.arange(n_items))
scores

array([-18.17905426, -21.10667419, -20.32022667, ..., -24.5527916 ,
       -24.32742882, -24.65486145])

In [ ]:
# let's sort the scores (times -1)
np.sort(-scores)

array([16.81943703, 17.00757408, 17.08006287, ..., 26.20787811,
       26.35297012, 26.51713943])

In [ ]:
# we actually want the position of the previous sorted list argsort better
np.argsort(-scores)

array([ 172,  167,   55, ...,  680,  109, 1191])

In [ ]:
# order the scores from most probable to lowest prob.
# and take the movies in that order
sorted_scores = np.argsort(-scores)
top_items =  movies['item_labels'][sorted_scores]

In [ ]:
# now let's see the top ten
top_items[:10]

array(['Princess Bride, The (1987)',
       'Monty Python and the Holy Grail (1974)', 'Pulp Fiction (1994)',
       'Star Wars (1977)', 'Empire Strikes Back, The (1980)',
       'Fargo (1996)', 'Brazil (1985)', 'Raising Arizona (1987)',
       'Raiders of the Lost Ark (1981)', 'Twelve Monkeys (1995)'],
      dtype=object)

## Let's wrap everything into a function

In [ ]:
def sample_recommendation(model, data, user_ids,top=3):
    # number of users and movies in training data
    n_users, n_items  = data['train'].shape

    
    # generate recommendations for each user we input
    for user_id in user_ids:
        # Movies they already like 
        # Mengambil item_label (judul movie) positif sesuai dengan user_id yg di inputkan
        already_seen = data['item_labels'][data['train'].tocsr()[user_id].indices]
        
        # Movies our model predict they will like
        scores = model.predict(user_id, np.arange(n_items))

        # rank them in order of most liked to least
        top_movies = data['item_labels'][np.argsort(-scores)]
        

        # print out what user has seen an the recommendataions        
        print("User %s"%user_id)
        print("   Already seen:")
        for x in already_seen[:top]:
            print("      %s" %x)
        
        print("Recomended : ")
        for x in top_movies[:top]:
            print("      %s" %x)

In [ ]:
sample_recommendation(rec_sys,movies,[11, 14, 25, 32,50, 80],5)

User 11
   Already seen:
      Get Shorty (1995)
      Mr. Holland's Opus (1995)
      Apollo 13 (1995)
      Star Wars (1977)
      Forrest Gump (1994)
Recomended : 
      Schindler's List (1993)
      Shawshank Redemption, The (1994)
      Raiders of the Lost Ark (1981)
      Forrest Gump (1994)
      When Harry Met Sally... (1989)
User 14
   Already seen:
      Dead Man Walking (1995)
      Postino, Il (1994)
      Mr. Holland's Opus (1995)
      Star Wars (1977)
      Truth About Cats & Dogs, The (1996)
Recomended : 
      Mr. Holland's Opus (1995)
      Sense and Sensibility (1995)
      English Patient, The (1996)
      Emma (1996)
      Postino, Il (1994)
User 25
   Already seen:
      Dead Man Walking (1995)
      Star Wars (1977)
      Fargo (1996)
      Spitfire Grill, The (1996)
      Godfather, The (1972)
Recomended : 
      L.A. Confidential (1997)
      English Patient, The (1996)
      Titanic (1997)
      Godfather, The (1972)
      Fargo (1996)
User 32
   Already seen:

## Exercise. Fix the previous recommendation system